### ISSUE TITLE
Bu burada şimdilik dursun issuesi

### ISSUE THREAD

**Issue by rasnesakam** [ytkimirti/minishell#13]
https://github.com/ytkimirti/minishell/blob/197c709e15dcbeb682e9172499c32c082cea1cf8/src/map/hashing.c#L43

Hocam buradaki asal sayı değeri sanırım şifreleyeceğimiz verilerin alfabesine göre değişiklik gösteriyor.
Yani eğer sadece küçük harflerden, ingiliz alfabesinden oluşan bir metni şifreleyeceksek 31 sayısını öneriyorlar. Eğer büyük harfler de dahil edilecekse 53.

Biz daha generic olsun diye void pointer yaptık ve bu durumda bizim alfabemiz 128 tane şeyden oluşuyor gibi düşünebiliriz. Bu durumda sanırım 128 e yakın bir asal sayı seçmeliyiz ama onu sonra şaaparız. Bu da burada dursun issuesi olarak açtım unutmayayım diye

**Comment by ytkimirti** [comment]
Başka bir şele artık
