### ISSUE TITLE
Hocam setenv çalışmıyor olabilir mi?

### ISSUE THREAD

**Issue by rasnesakam** [ytkimirti/minishell#39]
Hocam sürdürdüğüm çalışmalara dayanarak şunu söyleyebilirim ki.. setenv çalışmıyor olabilir.

**Comment by ytkimirti** [comment]
:O

**Comment by ytkimirti** [comment]
@rasnesakam hocam birdaha deneyebilir misin hatayı çözdüm sanırım ama emin olmak lazım

**Comment by rasnesakam** [comment]
Çalışıyor hocam eline sağlık
